name: kueski_challenge
description: Kueski App.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:

  flutter:
    sdk: flutter

  slang: ^3.30.1
  slang_flutter: ^3.30.0
  mobile_dependencies:
    path: packages/mobile_dependencies



dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^3.0.0




flutter:
  uses-material-design: true
  generate: true

