name: kueski_challenge
description: Kueski App.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:

  flutter:
    sdk: flutter


  flutter_riverpod: ^2.5.1
  go_router: ^13.2.1
  intl: ^0.19.0
  slang: ^3.30.1
  slang_flutter: ^3.30.0


dev_dependencies:

  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

